describe('Play game', () => {
  it('should display correct winner after vertical win', () => {
    cy
      .visit("/")
      .contains('Start Local co-op Game')
      .click()
      .get('h2')
      .should('contain', 'This is a Local Coop Game')
      .get('div[aria-label="column"]')
      .eq(0)
      .click()
      .wait(500)
      .get('div[aria-label="column"]')
      .eq(1)
      .click()
      .wait(500)
      .get('div[aria-label="column"]')
      .eq(0)
      .click()
      .wait(500)
      .get('div[aria-label="column"]')
      .eq(1)
      .click()
      .wait(500)
      .get('div[aria-label="column"]')
      .eq(0)
      .click()
      .wait(500)
      .get('div[aria-label="column"]')
      .eq(1)
      .click()
      .wait(500)
      .get('div[aria-label="column"]')
      .eq(0)
      .click()
      .wait(500)
      .get('h3')
      .should('contain', 'Player 1')
      .get('h2')
      .should('contain', 'WINNER')
  })
})
